#!/usr/bin/env python3
"""Generate the kube-ovn DRA NIC demo fixtures and scaling examples.

Produces, under demo/nic-example/:
  - 00-kube-ovn-subnets.yaml        (ProviderNetwork + 8 VLAN + 8 overlay subnets)
  - examples/<N>nic.yaml            (ResourceClaim + netshoot Pod with N NICs)

and prints the containerlab / FRR / bridge snippets needed for the VLAN underlay
to actually pass traffic (these are host-side and applied by `make clab-deploy`).

The demo attaches an equal split of underlay (VLAN) and overlay (OVN) NICs to a
netshoot pod, so the spin-up time can be measured against the Multus baseline
(~5s/NIC, serial) at increasing NIC counts.

Subnet scheme:
  underlay  vlan<100*i>-subnet  VLAN <100*i>  172.<22+i>.0.0/24  gw .253
  overlay   ovn-subnet[-i]      10.<199+i>.0.0/24                gw .1

Usage:
  python3 demo/nic-example/examples/generate.py        # default counts 2,4,8,16
  MAX_VLANS=8 COUNTS="2,6,12" python3 .../generate.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
NIC_DIR = os.path.dirname(HERE)

MAX_PAIRS = int(os.environ.get("MAX_VLANS", "8"))  # 8 underlay + 8 overlay available
COUNTS = [int(c) for c in os.environ.get("COUNTS", "2,4,8,16").split(",")]

CONFIG_API = "nic.resource.kube-ovn.io/v1alpha1"
NETSHOOT = "nicolaka/netshoot@sha256:47b907d662d139d1e2f22bfe14f4efca1e3f1feed283572f47c970c780c03b61"


def underlay(i):  # i = 1..MAX_PAIRS
    vid = 100 * i
    return {
        "vlan": f"vlan{vid}",
        "subnet": f"vlan{vid}-subnet",
        "id": vid,
        "cidr": f"172.{22 + i}.0.0/24",
        "gw": f"172.{22 + i}.0.253",
        "provider": f"external.vlan{vid}-subnet.ovn",
    }


def overlay(i):  # i = 1..MAX_PAIRS
    name = "ovn-subnet" if i == 1 else f"ovn-subnet-{i}"
    return {
        "subnet": name,
        "cidr": f"10.{199 + i}.0.0/24",
        "gw": f"10.{199 + i}.0.1",
        "provider": f"{name}.default.ovn",
    }


def write_subnets():
    out = [
        "# kube-ovn ProviderNetwork, VLANs and subnets for the DRA NIC driver demo.",
        "#",
        f"# {MAX_PAIRS} VLAN underlay subnets (vlan100-subnet .. vlan{100*MAX_PAIRS}-subnet) and",
        f"# {MAX_PAIRS} OVN overlay subnets (ovn-subnet, ovn-subnet-2 .. ovn-subnet-{MAX_PAIRS}).",
        "# The scaling examples under examples/ attach an equal split of these to a pod.",
        "#",
        "# GENERATED by examples/generate.py — edit there, not here.",
        "# VLAN underlay requires the matching containerlab wiring (make clab-deploy).",
        "---",
        "apiVersion: kubeovn.io/v1",
        "kind: ProviderNetwork",
        "metadata:",
        "  name: external",
        "spec:",
        "  defaultInterface: eth1",
    ]
    for i in range(1, MAX_PAIRS + 1):
        u = underlay(i)
        out += [
            "---",
            "apiVersion: kubeovn.io/v1",
            "kind: Vlan",
            "metadata:",
            f"  name: {u['vlan']}",
            "spec:",
            f"  id: {u['id']}",
            "  provider: external",
            "---",
            "apiVersion: kubeovn.io/v1",
            "kind: Subnet",
            "metadata:",
            f"  name: {u['subnet']}",
            "spec:",
            "  protocol: IPv4",
            f"  cidrBlock: {u['cidr']}",
            f"  # FRR gateway on eth1.{u['id']} (.253) is the L3 next-hop; .1 has no device.",
            f"  gateway: {u['gw']}",
            "  excludeIps:",
            f"    - {u['gw']}",
            f"    - 172.{22 + i}.0.254",
            f"  vlan: {u['vlan']}",
            f"  provider: {u['provider']}",
        ]
    for i in range(1, MAX_PAIRS + 1):
        o = overlay(i)
        out += [
            "---",
            "# OVN overlay subnet (no VLAN/eth1 dependency). Secondary OVN NICs need a",
            "# dedicated provider '<name>.<namespace>.ovn' (the default 'ovn' names eth0).",
            "apiVersion: kubeovn.io/v1",
            "kind: Subnet",
            "metadata:",
            f"  name: {o['subnet']}",
            "spec:",
            "  protocol: IPv4",
            f"  cidrBlock: {o['cidr']}",
            f"  gateway: {o['gw']}",
            f"  provider: {o['provider']}",
        ]
    path = os.path.join(NIC_DIR, "00-kube-ovn-subnets.yaml")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path)


def nic_entries(count):
    """Return list of (ifname, subnet, kind) with underlay first, equal split."""
    pairs = count // 2
    extra_underlay = count - 2 * pairs  # odd counts get one more underlay
    u_count = pairs + extra_underlay
    o_count = pairs
    if u_count > MAX_PAIRS or o_count > MAX_PAIRS:
        raise SystemExit(f"count {count} exceeds available {MAX_PAIRS} underlay/{MAX_PAIRS} overlay")
    entries = []
    idx = 1
    for i in range(1, u_count + 1):
        entries.append((f"net{idx}", underlay(i)["subnet"], "underlay"))
        idx += 1
    for i in range(1, o_count + 1):
        entries.append((f"net{idx}", overlay(i)["subnet"], "overlay"))
        idx += 1
    return entries


def write_example(count):
    entries = nic_entries(count)
    claim = f"pod-nic-{count}"
    pod = f"nic-demo-{count}"
    reqs, cfgs = [], []
    for n, (ifname, subnet, _) in enumerate(entries):
        reqs += [
            f"      - name: nic{n}",
            "        exactly:",
            "          deviceClassName: kube-ovn-nic",
            "          selectors:",
            "            - cel:",
            f"                expression: \"device.attributes['nic.kubeovn.io'].subnetName == '{subnet}'\"",
            "          count: 1",
        ]
        cfgs += [
            f"      - requests: [\"nic{n}\"]",
            "        opaque:",
            "          driver: nic.kubeovn.io",
            "          parameters:",
            f"            apiVersion: {CONFIG_API}",
            "            kind: NicConfig",
            f"            interfaceName: {ifname}",
        ]
    u = sum(1 for e in entries if e[2] == "underlay")
    o = sum(1 for e in entries if e[2] == "overlay")
    lines = [
        f"# Scaling example: {count} secondary NICs ({u} VLAN underlay + {o} OVN overlay)",
        f"# on a single netshoot pod. Run one example at a time (they share subnets).",
        "# GENERATED by examples/generate.py.",
        "#   kubectl apply -f this-file        (or: make nic-example-deploy COUNT={c})".format(c=count),
        "---",
        "apiVersion: resource.k8s.io/v1",
        "kind: ResourceClaim",
        "metadata:",
        f"  name: {claim}",
        "  namespace: default",
        "spec:",
        "  devices:",
        "    requests:",
        *reqs,
        "    config:",
        *cfgs,
        "---",
        "apiVersion: v1",
        "kind: Pod",
        "metadata:",
        f"  name: {pod}",
        "  namespace: default",
        "spec:",
        "  resourceClaims:",
        f"    - name: nics",
        f"      resourceClaimName: {claim}",
        "  containers:",
        "    - name: demo",
        f"      image: {NETSHOOT}",
        "      command: [\"sleep\", \"infinity\"]",
        "      resources:",
        "        claims:",
        "          - name: nics",
        "      securityContext:",
        "        capabilities:",
        "          add: [\"NET_ADMIN\"]",
    ]
    path = os.path.join(HERE, f"{count}nic.yaml")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path, f"({u} underlay + {o} overlay)")


def _peer_claim_pod(name, entries, control_plane):
    """Emit a ResourceClaim + netshoot Pod with the given (ifname, subnet) NICs."""
    reqs, cfgs = [], []
    for n, (ifname, subnet) in enumerate(entries):
        reqs += [
            f"      - name: net{n}",
            "        exactly:",
            "          deviceClassName: kube-ovn-nic",
            "          selectors:",
            "            - cel:",
            f"                expression: \"device.attributes['nic.kubeovn.io'].subnetName == '{subnet}'\"",
            "          count: 1",
        ]
        cfgs += [
            f"      - requests: [\"net{n}\"]",
            "        opaque:",
            "          driver: nic.kubeovn.io",
            "          parameters:",
            f"            apiVersion: {CONFIG_API}",
            "            kind: NicConfig",
            f"            interfaceName: {ifname}",
        ]
    pod = [
        "apiVersion: v1",
        "kind: Pod",
        "metadata:",
        f"  name: {name}",
        "  namespace: default",
        "  labels:",
        "    app: vlan-peer-test",
        "spec:",
    ]
    if control_plane:
        # Pin to the control-plane node (tolerate its taint). The worker-side
        # pod omits the toleration, so the scheduler lands it on the worker —
        # giving cross-node tagged traffic over the trunk.
        pod += [
            "  nodeSelector:",
            "    node-role.kubernetes.io/control-plane: \"\"",
            "  tolerations:",
            "    - key: node-role.kubernetes.io/control-plane",
            "      operator: Exists",
            "      effect: NoSchedule",
        ]
    pod += [
        "  resourceClaims:",
        "    - name: nics",
        f"      resourceClaimName: {name}-nic",
        "  containers:",
        "    - name: peer",
        f"      image: {NETSHOOT}",
        "      command: [\"sleep\", \"infinity\"]",
        "      resources:",
        "        claims:",
        "          - name: nics",
        "      securityContext:",
        "        capabilities:",
        "          add: [\"NET_ADMIN\"]",
    ]
    return [
        "apiVersion: resource.k8s.io/v1",
        "kind: ResourceClaim",
        "metadata:",
        f"  name: {name}-nic",
        "  namespace: default",
        "spec:",
        "  devices:",
        "    requests:",
        *reqs,
        "    config:",
        *cfgs,
        "---",
        *pod,
    ]


def write_vlan_peers():
    """07-vlan-peer-pod.yaml: one peer per VLAN on the control-plane + one
    worker-side pod with all VLANs, for the cross-node tagged-traffic test."""
    out = [
        f"# Per-VLAN connectivity test fixture ({MAX_PAIRS} VLANs).",
        "# GENERATED by examples/generate.py.",
        "#   vlan<N>-peer  (control-plane)  net1 on vlan<N>-subnet",
        "#   vlan-worker   (worker)         net1..netK across all VLAN subnets",
        "# Cross-node traffic crosses eth1 through the vlan-switch with 802.1q tags.",
    ]
    for i in range(1, MAX_PAIRS + 1):
        vid = 100 * i
        out += ["---"] + _peer_claim_pod(
            f"vlan{vid}-peer", [("net1", f"vlan{vid}-subnet")], control_plane=True
        )
    worker_entries = [(f"net{i}", underlay(i)["subnet"]) for i in range(1, MAX_PAIRS + 1)]
    out += ["---"] + _peer_claim_pod("vlan-worker", worker_entries, control_plane=False)
    path = os.path.join(NIC_DIR, "07-vlan-peer-pod.yaml")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, f"({MAX_PAIRS} peers + 1 worker pod)")


def print_clab_snippets():
    print("\n# ---- containerlab vlan-topology.yaml frr-gw exec (VLAN sub-interfaces) ----")
    for i in range(1, MAX_PAIRS + 1):
        u = underlay(i)
        print(f"        - ip link add link eth1 name eth1.{u['id']} type vlan id {u['id']}")
    for i in range(1, MAX_PAIRS + 1):
        u = underlay(i)
        print(f"        - ip addr add {u['gw']}/24 dev eth1.{u['id']}")
    for i in range(1, MAX_PAIRS + 1):
        u = underlay(i)
        print(f"        - ip link set eth1.{u['id']} up")
    print("\n# ---- Makefile clab-deploy: bridge vlan allows ----")
    vids = ",".join(str(underlay(i)["id"]) for i in range(1, MAX_PAIRS + 1))
    print(f"        for vid in {vids}; do for p in port1 port2 port3; do sudo bridge vlan add vid $$vid dev $$p; done; done")
    print("\n# ---- frr.conf VLAN-SUBNETS prefix-list ----")
    seq = 10
    for i in range(1, MAX_PAIRS + 1):
        u = underlay(i)
        net = u["cidr"]
        print(f"ip prefix-list VLAN-SUBNETS seq {seq} permit {net} le 32")
        seq += 10


# ---------------------------------------------------------------------------
# Benchmark fixtures: equivalent DRA vs Multus N-NIC pods, for spin-up timing
# (DRA structured-parameter allocation vs Multus serial NAD attach).
# ---------------------------------------------------------------------------

BENCH_VLAN_BASE = 1100  # bench underlay VLAN ids, distinct from the demo's 100..


def bench_overlay(i):
    # Reuse the demo overlay subnets: already enumerated by the driver and their
    # provider already matches the NAD pattern <subnet>.default.ovn.
    o = overlay(i)
    return {"subnet": o["subnet"], "provider": o["provider"], "new": False}


def bench_underlay(i):
    # The demo underlay providers (external.vlanX-subnet.ovn) do NOT fit the NAD
    # <name>.<ns>.ovn pattern, so the benchmark provisions its own underlay
    # subnets whose provider == <subnet>.default.ovn (NAD name == subnet name).
    name = f"bench-u{i}"
    return {
        "subnet": name,
        "provider": f"{name}.default.ovn",
        "vlan": f"bench-vlan{i}",
        "id": BENCH_VLAN_BASE + i,
        "cidr": f"10.{210 + i}.0.0/24",
        "gw": f"10.{210 + i}.0.1",
        "new": True,
    }


def bench_entries(mode, count):
    if mode == "overlay":
        if count > MAX_PAIRS:
            raise SystemExit(f"overlay count {count} exceeds {MAX_PAIRS} subnets")
        items = [bench_overlay(i) for i in range(1, count + 1)]
    elif mode == "underlay":
        if count > MAX_PAIRS:
            raise SystemExit(f"underlay count {count} exceeds {MAX_PAIRS} subnets")
        items = [bench_underlay(i) for i in range(1, count + 1)]
    elif mode == "mixed":
        pairs = count // 2
        u_count = pairs + (count - 2 * pairs)  # odd -> one more underlay
        o_count = pairs
        if u_count > MAX_PAIRS or o_count > MAX_PAIRS:
            raise SystemExit(f"mixed count {count} exceeds {MAX_PAIRS}/{MAX_PAIRS}")
        items = [bench_underlay(i) for i in range(1, u_count + 1)]
        items += [bench_overlay(i) for i in range(1, o_count + 1)]
    else:
        raise SystemExit(f"unknown mode {mode!r}")
    for n, it in enumerate(items, start=1):
        it["ifname"] = f"net{n}"
    return items


def _write(path, lines):
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path)


def write_bench(mode, count, outdir):
    os.makedirs(outdir, exist_ok=True)
    entries = bench_entries(mode, count)

    # Benchmark subnets — only the underlay ones need creating (overlay reuses
    # the demo subnets). Deploy these BEFORE/with a plugin restart so the driver
    # enumerates them. Needs ProviderNetwork external (eth1 via clab).
    new = [e for e in entries if e["new"]]
    subnets_path = os.path.join(outdir, "subnets.yaml")
    if new:
        out = [
            "# Benchmark underlay subnets (Multus-compatible <name>.default.ovn providers).",
            "# GENERATED by generate.py bench. Needs ProviderNetwork external (eth1 via clab).",
            "---", "apiVersion: kubeovn.io/v1", "kind: ProviderNetwork",
            "metadata:", "  name: external", "spec:", "  defaultInterface: eth1",
        ]
        for e in new:
            out += [
                "---", "apiVersion: kubeovn.io/v1", "kind: Vlan", "metadata:",
                f"  name: {e['vlan']}", "spec:", f"  id: {e['id']}", "  provider: external",
                "---", "apiVersion: kubeovn.io/v1", "kind: Subnet", "metadata:",
                f"  name: {e['subnet']}", "spec:", "  protocol: IPv4",
                f"  cidrBlock: {e['cidr']}", f"  gateway: {e['gw']}",
                f"  vlan: {e['vlan']}", f"  provider: {e['provider']}",
            ]
        _write(subnets_path, out)
    elif os.path.exists(subnets_path):
        os.remove(subnets_path)

    # DRA fixture: one ResourceClaim with N requests + a netshoot pod.
    reqs, cfgs = [], []
    for n, e in enumerate(entries):
        reqs += [
            f"      - name: nic{n}", "        exactly:",
            "          deviceClassName: kube-ovn-nic", "          selectors:",
            "            - cel:",
            f"                expression: \"device.attributes['nic.kubeovn.io'].subnetName == '{e['subnet']}'\"",
            "          count: 1",
        ]
        cfgs += [
            f"      - requests: [\"nic{n}\"]", "        opaque:",
            "          driver: nic.kubeovn.io", "          parameters:",
            f"            apiVersion: {CONFIG_API}", "            kind: NicConfig",
            f"            interfaceName: {e['ifname']}",
        ]
    dra = [
        f"# DRA benchmark: {count} NICs ({mode}). GENERATED by generate.py bench.",
        "---", "apiVersion: resource.k8s.io/v1", "kind: ResourceClaim",
        "metadata:", "  name: bench-dra", "  namespace: default", "spec:",
        "  devices:", "    requests:", *reqs, "    config:", *cfgs,
        "---", "apiVersion: v1", "kind: Pod", "metadata:", "  name: bench-dra",
        "  namespace: default", "spec:", "  resourceClaims:", "    - name: nics",
        "      resourceClaimName: bench-dra", "  containers:", "    - name: demo",
        f"      image: {NETSHOOT}", "      command: [\"sleep\", \"infinity\"]",
        "      resources:", "        claims:", "          - name: nics",
        "      securityContext:", "        capabilities:", "          add: [\"NET_ADMIN\"]",
    ]
    _write(os.path.join(outdir, "dra.yaml"), dra)

    # Multus fixture: N NetworkAttachmentDefinitions + a netshoot pod annotated
    # with all of them. kube-ovn reads the provider from the NAD's CNI config.
    nets = ", ".join(f"default/{e['subnet']}@{e['ifname']}" for e in entries)
    mu = [f"# Multus benchmark: {count} NICs ({mode}). GENERATED by generate.py bench."]
    for e in entries:
        cfg = ('{"cniVersion":"0.3.0","type":"kube-ovn",'
               '"server_socket":"/run/openvswitch/kube-ovn-daemon.sock",'
               f'"provider":"{e["provider"]}"}}')
        mu += [
            "---", "apiVersion: k8s.cni.cncf.io/v1",
            "kind: NetworkAttachmentDefinition", "metadata:",
            f"  name: {e['subnet']}", "  namespace: default", "spec:",
            f"  config: '{cfg}'",
        ]
    mu += [
        "---", "apiVersion: v1", "kind: Pod", "metadata:", "  name: bench-multus",
        "  namespace: default", "  annotations:",
        f"    k8s.v1.cni.cncf.io/networks: {nets}", "spec:", "  containers:",
        "    - name: demo", f"      image: {NETSHOOT}",
        "      command: [\"sleep\", \"infinity\"]", "      securityContext:",
        "        capabilities:", "          add: [\"NET_ADMIN\"]",
    ]
    _write(os.path.join(outdir, "multus.yaml"), mu)


def _run_bench_cli():
    import argparse
    p = argparse.ArgumentParser(prog="generate.py bench")
    p.add_argument("--mode", choices=["overlay", "underlay", "mixed"], default="overlay")
    p.add_argument("--count", type=int, required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args(sys.argv[2:])
    write_bench(args.mode, args.count, args.out)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "bench":
        _run_bench_cli()
    else:
        write_subnets()
        for c in COUNTS:
            write_example(c)
        write_vlan_peers()
        print_clab_snippets()
