# DeviceClass for NIC devices managed by our kube-ovn DRA driver.
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: kube-ovn-nic
spec:
  selectors:
    - cel:
        expression: "device.driver == 'nic.kubeovn.io'"
